services:
  web:
    build: .
    container_name: task_sphere_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ../../TaskSphereReact/TaskSphereReact/reactapp
    container_name: task_sphere_react
    ports:
      - "3000:3000"
    volumes:
      - ../../TaskSphereReact/TaskSphereReact/reactapp:/app
    stdin_open: true
    tty: true