version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable

    # Add steps to the job
    steps:
      # Checkout the code as the first step.
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t tasksphere-django .

workflows:
  django-integration:  
    jobs:
      - build-and-test
